#version: '3.9'
services:
  redis:
    image: redis:6.2.6-alpine
    restart: always
    ports:
      - 5200:6379
    command: redis-server --requirepass pass
#    networks:
#      - gratheon
#networks:
#  gratheon: